// Content-Security-Policy for the static site (spec 7.3, 9).
// Next.js puts small inline scripts in every exported page; instead of 'unsafe-inline' the
// policy allows exactly those scripts by their SHA-256 hash, recomputed on every build.
//
//   node scripts/csp.mjs out > csp.caddy     (Caddy header directive, used by deploy/web)
//
// In the Caddy file the CMS origin stays a placeholder ({$CMS_ORIGIN:}) that Caddy fills from
// the environment when it starts, so one image works for any domain.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

function* htmlFiles(d) {
  for (const name of readdirSync(d)) {
    const p = join(d, name);
    if (statSync(p).isDirectory()) yield* htmlFiles(p);
    else if (name.endsWith(".html")) yield p;
  }
}

export function buildPolicy(dir, cmsOrigin = "") {
  const scripts = new Set();
  for (const file of htmlFiles(dir)) {
    const text = readFileSync(file, "utf8");
    for (const m of text.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
      if (m[1]) scripts.add(`'sha256-${createHash("sha256").update(m[1]).digest("base64")}'`);
    }
    if (/<style[\s>]|\sstyle="/.test(text)) throw new Error(`${file}: inline styles are not allowed by the CSP`);
  }
  return [
    "default-src 'none'",
    `script-src 'self' ${[...scripts].sort().join(" ")}`,
    "style-src 'self'",
    "img-src 'self' data: blob:",
    "font-src 'self'",
    `connect-src 'self'${cmsOrigin ? ` ${cmsOrigin}` : ""}`,
    "manifest-src 'self'",
    "base-uri 'none'",
    "form-action 'none'",
    "frame-ancestors 'none'",
    "object-src 'none'",
    "upgrade-insecure-requests",
  ].join("; ");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try {
    const policy = buildPolicy(process.argv[2] ?? "out", "{$CMS_ORIGIN:}");
    process.stdout.write(`# generated by web/scripts/csp.mjs at build time\nheader Content-Security-Policy "${policy}"\n`);
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}
